export enum MaterialType {
  ELECTRONICO = 'ELECTRONICO',
  MECANICO = 'MECANICO',
  QUIMICO = 'QUIMICO', 
  TEXTIL = 'TEXTIL',
  CONSTRUCCION = 'CONSTRUCCION',
  HERRAMIENTA = 'HERRAMIENTA',
  OFICINA = 'OFICINA'
}